name: tests
on: [pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Touch local properties
        run: touch local.properties

      - name: Add Api Key
        run: echo "apiKey=\"\"" >> local.properties

      - name: Run Tests
        run: ./gradlew test
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew assembleDebug
